feat: Update deployment workflow to Node 20 and use GitHub Pages Actions
- Updated Node version to 20.
- Implemented GitHub Pages Actions for deployment.
- Retried rendering to increase flakiness tolerance.

diff --git a/.github/workflow/deploy.yml b/.github/workflow/deploy.yml
--- a/.github/workflow/deploy.yml
+++ b/.github/workflow/deploy.yml
@@ -9,26 +9,48 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
-          node-version: '16'
-
-      - name: Cache dependencies
-        uses: actions/cache@v3
-        with:
-          path: ~/.npm
-          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.OS }}-node-
+          node-version: '20'
+          cache: 'npm'
 
       - run: npm ci
-      - run: npm run build
+      
+      - name: Build and Render
+        shell: bash
+        run: |
+          # NOTE: Rendering can be flaky and react-snap is no
+          # longer maintained, so retry until I convert to next.
+          function retry {
+            local n=1
+            local max=5
+            local delay=1
+            while true; do
+              "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                  ((n++))
+                  echo "Command failed. Attempt $n/$max:"
+                  sleep $delay;
+                else
+                  echo "The command has failed after $n attempts."
+                  return 1
+                fi
+              }
+            done
+          }
+          retry npm run predeploy
 
-      - name: Deploy
-        uses: peaceiris/actions-gh-pages@v3
+      - name: Setup Pages
+        uses: actions/configure-pages@v3
+
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v2
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./build
+          path: "build"
+
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v2
